# This is a basic workflow to help you get started with Actions

name: Config Deploy

# Controls when the workflow will run
on:
  workflow_dispatch:
  repository_dispatch:
    types: [Config Deploy (Apply)]

jobs:
  dispatch-config:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write
      packages: read
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
        repository: tarathep/app-poc-action-config
        event-type: Get Config
  

  get-secret:
    if: ${{ github.event_name == 'repository_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Test remote repo with remote personal token secret
        run: |
          echo "Some secret here. ${{ github.event.client_payload.test_secret }}" > myfile.txt
          cat myfile.txt
         
     