# This is a basic workflow to help you get started with Actions

name: Receive

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [receive-secret]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dispatch-config:
    if: github.event.name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo hello

    # permissions:
    #   actions: read
    #   contents: write
    #   security-events: write
    #   packages: read
    # steps:
    # - name: Repository Dispatch
    #   uses: peter-evans/repository-dispatch@v2
    #   with:
    #     token: ${{ secrets.WORKFLOW_TOKEN }}
    #     repository: tarathep/app-poc-receive-config
    #     event-type: receive-secret
    #     client-payload: '{"repository": "${{ github.repository }}" , "ref": "${{ github.ref }}", "test_secret": "${{ secrets.TEST_SECRET }}", "github_token": "${{ secrets.WORKFLOW_TOKEN }}"}'
  
  
  # get-secret:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3
      
  #     - name: Test remote repo with remote personal token secret
  #       run: |
  #         echo "Some secret here. ${{ github.event.client_payload.test_secret }}" > myfile.txt
  #         cat myfile.txt
         
     